/**
 * Golden Dataset — Full Evaluation
 *
 * For each golden chat (by chatId):
 *   1. Calls the generate-ai API to produce a fresh draft
 *   2. Saves snapshot to conversations/{id}.json
 *   3. Runs invariant checks on the result
 *
 * Requires:
 *   - Running Next.js server (or direct DB access)
 *   - Valid auth token (R5_EVAL_TOKEN env var or r5_token cookie)
 *
 * Usage:
 *   R5_EVAL_TOKEN=xxx npx tsx tests/golden/evaluate.ts
 *
 * PR-07
 */

import * as fs from 'fs';
import * as path from 'path';
import { validateDraft, type ValidatorContext } from '../../src/ai/output-validator';

const BASE_URL = process.env.R5_BASE_URL || 'https://rating5.ru';
const AUTH_TOKEN = process.env.R5_EVAL_TOKEN || '';

interface GoldenConfig {
  id: string;
  chatId: string;
  storeId: string;
  marketplace: 'wb' | 'ozon';
  expectedRating: number | null;
  expectedPhase: 'discovery' | 'proposal' | 'resolution';
}

// ============================================================================
// Configure golden chats here (fill with real IDs)
// ============================================================================
const GOLDEN_CHATS: GoldenConfig[] = [
  // Uncomment and fill with real values:
  // { id: 'GOLDEN-WB-DISC', chatId: 'xxx', storeId: 'xxx', marketplace: 'wb', expectedRating: 2, expectedPhase: 'discovery' },
  // { id: 'GOLDEN-WB-LOW', chatId: 'xxx', storeId: 'xxx', marketplace: 'wb', expectedRating: 2, expectedPhase: 'resolution' },
  // { id: 'GOLDEN-WB-HIGH', chatId: 'xxx', storeId: 'xxx', marketplace: 'wb', expectedRating: 4, expectedPhase: 'proposal' },
  // { id: 'GOLDEN-OZON', chatId: 'xxx', storeId: 'xxx', marketplace: 'ozon', expectedRating: 3, expectedPhase: 'proposal' },
];

const CONVERSATIONS_DIR = path.join(__dirname, 'conversations');

async function generateDraft(storeId: string, chatId: string): Promise<{ draft: string } | null> {
  try {
    const res = await fetch(`${BASE_URL}/api/stores/${storeId}/chats/${chatId}/generate-ai`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Cookie': `r5_token=${AUTH_TOKEN}`,
      },
    });

    if (!res.ok) {
      console.error(`  API error ${res.status}: ${await res.text()}`);
      return null;
    }

    const data = await res.json();
    return { draft: data.draftReply || data.draft_reply || '' };
  } catch (err: any) {
    console.error(`  Fetch error: ${err.message}`);
    return null;
  }
}

async function main() {
  if (GOLDEN_CHATS.length === 0) {
    console.log('No golden chats configured. Edit tests/golden/evaluate.ts to add real chat IDs.');
    process.exit(0);
  }

  if (!AUTH_TOKEN) {
    console.error('Set R5_EVAL_TOKEN env var with a valid auth token.');
    process.exit(1);
  }

  console.log(`\nEvaluating ${GOLDEN_CHATS.length} golden chat(s) against ${BASE_URL}...\n`);

  let totalErrors = 0;

  for (const config of GOLDEN_CHATS) {
    console.log(`→ ${config.id} (chat=${config.chatId})...`);

    const result = await generateDraft(config.storeId, config.chatId);
    if (!result) {
      console.log(`  SKIP — could not generate draft`);
      continue;
    }

    // Save snapshot
    const snapshot = {
      id: config.id,
      chatId: config.chatId,
      marketplace: config.marketplace,
      reviewRating: config.expectedRating,
      phase: config.expectedPhase,
      sellerMessageCount: 0, // Will be filled from actual data if available
      draft: result.draft,
      generatedAt: new Date().toISOString(),
      promptVersion: parseInt(process.env.AI_PROMPT_VERSION || '1', 10),
      manualScore: null,
      notes: 'Auto-generated by evaluate.ts',
    };

    const snapshotPath = path.join(CONVERSATIONS_DIR, `${config.id}.json`);
    fs.writeFileSync(snapshotPath, JSON.stringify(snapshot, null, 2), 'utf-8');
    console.log(`  Saved → ${snapshotPath}`);

    // Validate
    const ctx: ValidatorContext = {
      marketplace: config.marketplace,
      reviewRating: config.expectedRating,
      phase: config.expectedPhase,
      sellerMessageCount: 0,
      chatId: config.chatId,
    };

    const validation = validateDraft(result.draft, ctx);
    const errors = validation.violations.filter(v => v.severity === 'error');
    const warnings = validation.violations.filter(v => v.severity === 'warning');

    if (errors.length === 0) {
      console.log(`  ✓ PASS (${result.draft.length} chars, ${warnings.length} warning(s))`);
    } else {
      console.log(`  ✗ FAIL — ${errors.length} error(s):`);
      errors.forEach(e => console.log(`    ERROR: ${e.message}`));
      totalErrors += errors.length;
    }

    if (warnings.length > 0) {
      warnings.forEach(w => console.log(`    WARN: ${w.message}`));
    }

    // Rate-limit between calls
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log(`\n${'='.repeat(50)}`);
  if (totalErrors > 0) {
    console.log(`FAILED — ${totalErrors} invariant error(s).`);
    process.exit(1);
  } else {
    console.log('PASSED — all golden chats within invariants.');
  }
}

main();
