-- ============================================
-- WB Reputation Manager: Add Review Status Fields
-- Date: 2026-01-09
-- Description: Add status fields from Chrome extension parsing
-- ============================================

-- ============================================
-- Create ENUM Types for Statuses
-- ============================================

-- Review status on WB (from extension parsing)
CREATE TYPE review_status_wb AS ENUM (
  'visible',           -- Виден
  'unpublished',       -- Снят с публикации
  'excluded',          -- Исключён из рейтинга
  'unknown'            -- Неизвестно (по умолчанию)
);

-- Product status by review (from extension parsing)
CREATE TYPE product_status_by_review AS ENUM (
  'purchased',         -- Выкуп
  'refused',           -- Отказ
  'not_specified',     -- Не указано
  'unknown'            -- Неизвестно
);

-- Chat status by review (from extension parsing)
CREATE TYPE chat_status_by_review AS ENUM (
  'unavailable',       -- Недоступен
  'available',         -- Доступен
  'unknown'            -- Неизвестно
);

-- Complaint status (from extension parsing + manual tracking)
CREATE TYPE complaint_status AS ENUM (
  'not_sent',          -- Не отправлена
  'draft',             -- Черновик (сгенерирован, но не отправлен)
  'sent',              -- Отправлена (вручную отмечено)
  'approved',          -- Одобрена (от WB)
  'rejected',          -- Отклонена (от WB)
  'pending'            -- На рассмотрении (от WB)
);

COMMENT ON TYPE review_status_wb IS 'Review visibility status on Wildberries platform';
COMMENT ON TYPE product_status_by_review IS 'Product purchase status from review';
COMMENT ON TYPE chat_status_by_review IS 'Chat availability status from review';
COMMENT ON TYPE complaint_status IS 'Complaint submission and approval status';

-- ============================================
-- Add Status Columns to reviews Table
-- ============================================

-- Add new status columns
ALTER TABLE reviews
  ADD COLUMN IF NOT EXISTS review_status_wb review_status_wb DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS product_status_by_review product_status_by_review DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS chat_status_by_review chat_status_by_review DEFAULT 'unknown',
  ADD COLUMN IF NOT EXISTS complaint_status complaint_status DEFAULT 'not_sent',
  ADD COLUMN IF NOT EXISTS complaint_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS complaint_reason_id INTEGER,
  ADD COLUMN IF NOT EXISTS complaint_category TEXT,
  ADD COLUMN IF NOT EXISTS purchase_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS parsed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS page_number INTEGER;

COMMENT ON COLUMN reviews.review_status_wb IS 'Review visibility status on WB (parsed from extension)';
COMMENT ON COLUMN reviews.product_status_by_review IS 'Product purchase status (parsed from extension)';
COMMENT ON COLUMN reviews.chat_status_by_review IS 'Chat availability (parsed from extension)';
COMMENT ON COLUMN reviews.complaint_status IS 'Complaint processing status';
COMMENT ON COLUMN reviews.complaint_generated_at IS 'When complaint was generated by AI';
COMMENT ON COLUMN reviews.complaint_reason_id IS 'WB complaint reason ID';
COMMENT ON COLUMN reviews.complaint_category IS 'WB complaint category';
COMMENT ON COLUMN reviews.purchase_date IS 'Product purchase date';
COMMENT ON COLUMN reviews.parsed_at IS 'When review was parsed by extension';
COMMENT ON COLUMN reviews.page_number IS 'Page number where review was found';

-- ============================================
-- Create Indexes for Performance
-- ============================================

-- Index for filtering by complaint status (most common filter)
CREATE INDEX IF NOT EXISTS idx_reviews_complaint_status
  ON reviews(store_id, complaint_status, rating, date DESC)
  WHERE complaint_status = 'not_sent';

-- Index for filtering by review status on WB
CREATE INDEX IF NOT EXISTS idx_reviews_wb_status
  ON reviews(store_id, review_status_wb, date DESC);

-- Index for filtering by product status
CREATE INDEX IF NOT EXISTS idx_reviews_product_status
  ON reviews(store_id, product_status_by_review, date DESC);

-- Composite index for default filter (1-3 stars, active products, no complaint)
CREATE INDEX IF NOT EXISTS idx_reviews_default_filter
  ON reviews(store_id, rating, is_product_active, complaint_status, date DESC)
  WHERE rating <= 3 AND is_product_active = TRUE AND complaint_status IN ('not_sent', 'draft');

-- Index for complaint management queries
CREATE INDEX IF NOT EXISTS idx_reviews_complaint_workflow
  ON reviews(store_id, complaint_status, complaint_generated_at DESC)
  WHERE complaint_status IN ('draft', 'sent', 'pending');

COMMENT ON INDEX idx_reviews_complaint_status IS 'Optimized for "Требуют внимания" filter';
COMMENT ON INDEX idx_reviews_default_filter IS 'Optimized for default page load (1-3 stars, active, no complaint)';
COMMENT ON INDEX idx_reviews_complaint_workflow IS 'Optimized for complaint management workflow';

-- ============================================
-- Update Existing Data
-- ============================================

-- Update complaint_status based on existing data
UPDATE reviews
SET complaint_status = CASE
  WHEN complaint_sent_date IS NOT NULL THEN 'sent'::complaint_status
  WHEN complaint_text IS NOT NULL THEN 'draft'::complaint_status
  ELSE 'not_sent'::complaint_status
END
WHERE complaint_status = 'not_sent';

-- Update has_complaint_draft based on new complaint_status
UPDATE reviews
SET has_complaint_draft = (complaint_status = 'draft')
WHERE has_complaint_draft != (complaint_status = 'draft');

-- ============================================
-- Add Triggers for Auto-Update Denormalized Fields
-- ============================================

-- Function to update has_complaint_draft based on complaint_status
CREATE OR REPLACE FUNCTION update_review_complaint_flags()
RETURNS TRIGGER AS $$
BEGIN
  -- Update has_complaint_draft
  NEW.has_complaint_draft = (NEW.complaint_status = 'draft');

  -- Update has_complaint
  NEW.has_complaint = (NEW.complaint_status IN ('sent', 'approved', 'rejected', 'pending'));

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update denormalized flags
CREATE TRIGGER update_reviews_complaint_flags
  BEFORE INSERT OR UPDATE OF complaint_status, complaint_text, complaint_sent_date
  ON reviews
  FOR EACH ROW
  EXECUTE FUNCTION update_review_complaint_flags();

COMMENT ON FUNCTION update_review_complaint_flags IS 'Auto-update has_complaint and has_complaint_draft based on complaint_status';

-- ============================================
-- Summary
-- ============================================

-- Added:
-- - 4 new ENUM types for statuses
-- - 10 new columns to reviews table
-- - 5 new performance indexes
-- - 1 trigger for auto-updating denormalized fields
--
-- Ready to:
-- 1. Receive data from Chrome extension
-- 2. Filter reviews by multiple status criteria
-- 3. Track complaint workflow from draft to approval
-- 4. Handle 1M+ reviews with optimized queries
